name: Matrix test

on:
  push:

jobs:
  deploy-on-ubuntu:
    strategy:
      fail-fast: false # Don't fail the whole workflow if one job fails
      max-parallel: 2 # Run 2 jobs in parallel
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, alpine]
        exclude:
          - os: windows-latest
            image: alpine
    runs-on: ${{ matrix.os }}

    steps:
      - name: Echo Docker Details for image ${{ matrix.image }} on os ${{ matrix.os }}
        run: docker info

      - name: Run Images for image ${{ matrix.image }} on os ${{ matrix.os }}
        run: docker run ${{ matrix.image }}
