name: Matrix test

on:
  push:
  workflow_dispatch:

jobs:
  deploy-on-ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu:latest
          - windows:latest
        image: ["hello-world", "alpine"]
    runs-on: ${{ matrix.os }}
    container: docker
    steps:
      - name: Echo Docker Details on image ${{ matrix.image }} os ${{ matrix.os }} version ${{ matrix.version }}
        run: docker info

      - name: Run Images on image ${{ matrix.image }} os ${{ matrix.os }} version ${{ matrix.version }}
        run: docker run ${{ matrix.image }}
