name: Matrix test

on:
  push:
  workflow_dispatch:

jobs:
  deploy-on-ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
        version: ["latest", "20.04"]
        image: ["hello-world", "alpine"]
        exclude:
          - os: windows
            version: "20.04"
    runs-on: ${{ matrix.os }}-${{ matrix.version }}
    container: docker
    steps:
      - name: Echo Docker Details on image ${{ matrix.image }} os ${{ matrix.os }} version ${{ matrix.version }}
        run: docker info

      - name: Run Images on image ${{ matrix.image }} os ${{ matrix.os }} version ${{ matrix.version }}
        run: docker run ${{ matrix.image }}
