#name: Exploring Variable and Secrets
# on:
#     push

# jobs:
# docker:
#   runs-on: ubuntu-latest
#   steps:
#     - name: docker build
#       run: docker build -t docker.io/dockerUsername/imageName:tag

#     - name: docker login
#       run: docker login -u dockerUsername -p dockerPassword

#     - name: docker push
#       run: docker push docker.io/dockerUsername/imageName:tag

# deploy:
#   needs: docker
#   runs-on: ubuntu-latest
#   steps:
#     - name: docker run
#       run: docker run -d -p 8080:80 docker.io/dockerUsername/imagename:tag

############################## Environment Variables at step level #############################

# docker:
#   runs-on: ubuntu-latest
#   steps:
#     - name: docker build
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USER: anishk03
#         IMAGE_NAME: github-actions-nginx
#         TAG: latest
#       run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$TAG

#     - name: docker login
#       env:
#         DOCKER_USER: anishk03
#         DOCKER_PASSWORD: black_man%%
#       run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

#     - name: docker push
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USER: anishk03
#         IMAGE_NAME: github-actions-nginx
#         TAG: latest
#       run: docker push $CONTAINER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$TAG

# deployment:
#   needs: docker
#   runs-on: ubuntu-latest
#   steps:
#     - name: docker run
#       env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USER: anishk03
#         IMAGE_NAME: github-actions-nginx
#         TAG: latest
#       run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$TAG

############################## Environment Variables at job level #############################

# docker:
#   runs-on: ubuntu-latest
#   env:
#     CONTAINER_REGISTRY: docker.io
#     DOCKER_USER: anishk03
#     IMAGE_NAME: github-actions-nginx
#     TAG: latest
#   steps:
#     - name: docker build
#       run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$TAG

#     - name: docker login
#       run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

#     - name: docker push
#       run: docker push $CONTAINER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$TAG

# deployment:
#   needs: docker
#   runs-on: ubuntu-latest
#   env:
#     CONTAINER_REGISTRY: docker.io
#     DOCKER_USER: anishk03
#     IMAGE_NAME: github-actions-nginx
#     TAG: latest
#   steps:
#     - name: docker run
#       run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USER/$IMAGE_NAME:$TAG

############################## Environment Variables at workflow level #############################

name: workflow variable at workflow level
on:
  schedule:
    - cron: "1 * * * *"
  #push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
  TAG: latest

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: docker build
        run: echo "docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"

      - name: docker login
        env:
          DOCKER_PASSWORD: black212369
        run: echo "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASS }}"

      - name: docker push
        run: echo "docker push ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"

  deployment:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: docker run
        run: echo "docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
